name: Setup OpenModelica
author: Kristian Zarebski
description: Setup installation of OpenModelica

inputs:
  libraries:
    description: OpenModelica Libraries to Install
    required: false
    default: ''
  msl-version:
    description: Version of Modelica Standard Library
    required: false
    default: '4.0.0'
  cpp-runtime-library:
    description: Install C++ Runtime Library
    required: false
    default: 'false'
  model-name:
    description: Name of model to build
    required: false
    default: 'false'
  model-source-path:
    description: Path to modelica source to build and run
    required: false
    default: 'false'
  script-path:
    description: Path to Modelica script .mos file
    required: false
    default: ''
  script:
    description: Modelica script to run
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install OpenModelica
      run: |
        INSTALL_OMC_CPP_LIBS=${{ inputs.cpp-runtime-library }} \
        MODEL_SOURCE_PATH=${{ inputs.model-source-path }} \
        MODEL_NAME=${{ inputs.model-name }} \
        $GITHUB_ACTION_PATH/install-om.sh Modelica@${{ inputs.msl-version }} $(echo "${{ inputs.libraries }}" | xargs)
      shell: bash

    - name: Run Modelica Script
      run: |
        if [ -z "${{ inputs.script-path }}" ]; then echo "No OMShell script to run"; exit 0; fi
        omc ${{ inputs.script-path }}
      shell: bash

    - name: Run OMShell
      run: |
        if [ -z "${{ inputs.script }}" ]; then echo "No OMShell commands to run"; exit 0; fi
        printf '${{ inputs.script }}' > runScript.mos
        echo "Created script: "
        cat runScript.mos
        omc runScript.mos
      shell: bash

branding:
  icon: trending-up
  color: blue

