
name: OpenModelica Action Check
on: [release]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: artemis-beta/setup-openmodelica@testing
          with:
            libraries: |
                PowerGrids
                SystemDynamics@2.1.1
            cpp-runtime-library: install
            model-source-path: testing/SineCurrent.mo
            model-name: SineCurrentModel
            debug: 'yes'
            msl-version: '3.2.3'
            script: |
              loadLibrary(Modelica);
              simulate(Modelica.Fluid.Examples.HeatSystem);
              printErrorString();

        - name: Test OMC Still Available
          run: omc --version
        

