
name: OpenModelica Action Check
on: [release]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: artemis-beta/setup-openmodelica@testing
          with:
            libraries: |
                PowerGrids
                SystemDynamics@2.1.1
            cpp-runtime-library: install
            model-source-path: testing/SineCurrent.mo
            model-name: SineCurrentModel
            msl-version: '3.2.3'
            script: |
              loadLibrary(Modelica);
              simulate(Modelica.Fluid.Examples.HeatSystem);
              getErrorString();

        - name: Test OMC Still Available
          run: omc --version

        - name: Cache Solutions
          uses: actions/cache@v2
          with:
            path: "*.mat"
            key: ${{ runner.os }}-model-solutions
        
        - name: Check results files still exist
          run: if [ -z "$(ls *.mat)" ]; then exit 1; fi
